title: Study Space
description: > # this means to ignore newlines until "baseurl:"
 majoring in software at Kookmin University in Seoul<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kimjinmyeong.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'JinMyeong'
  last_name: 'Kim'
<<<<<<< HEAD
  cv: ''
  avatar: '/images/avatar.jpeg'
  github_username:  kimjinmyeong
  email: kjmdkdlel@gmail.com
  vk_id: 
=======
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  kimjinmyeong
  email: kjmdkdlel@gmail.com
  vk_id: id201664979
>>>>>>> origin/main
  telegram_name: 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

